import {Inter} from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <nav>
                    <ul>
                        <li>
                            <Link href="/">홈</Link>
                        </li>
                        <li>
                            <Link href="/dog">강아지</Link>
                        </li>
                        <li>
                            <Link href="/cat">고양이</Link>
                        </li>
                    </ul>
                </nav>
                {children}
            </body>
        </html>
    );
}
